version: '3'
services:
  app:
    build: .
    environment:
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
